### ISSUE TITLE
Having issues in the logs

### ISSUE THREAD

**Issue by meneer-code** [niceboygithub/AqaraCamera#6]
Hi there

Thanks so much for the plugin. I'm just struggling to get it going, I'm getting these 2 errors:

```
Logger: homeassistant.components.camera
Source: custom_components/aqara_camera/camera.py:52 
Integration: Camera ([documentation](https://www.home-assistant.io/integrations/camera), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+camera%22)) 
First occurred: 18:19:37 (1 occurrences) 
Last logged: 18:19:37

Error while setting up aqara_camera platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aqara_camera/camera.py", line 52, in async_setup_entry
    raise CannotConnect
custom_components.aqara_camera.camera.CannotConnect
```

```
Logger: homeassistant.config_entries
Source: custom_components/aqara_camera/__init__.py:42 
Integration: Aqara Camera ([documentation](https://github.com/niceboygithub/AqaraCamera), [issues](https://github.com/niceboygithub/AqaraCamera/issues)) 
First occurred: 18:19:14 (1 occurrences) 
Last logged: 18:19:14

Error setting up entry Camera-Hub-G3-0794 for aqara_camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/aqara_camera/__init__.py", line 42, in async_setup_entry
    raise CannotConnect
custom_components.aqara_camera.core.exceptions.CannotConnect
```

**Comment by niceboygithub** [comment]
Did you enable telnet?

**Comment by amaisano** [comment]
@meneer-code how did you get these entries into your log? I think I might have the same problem but I can't see these logs.

I have enabled telnet (and tested via CLI that it works).

My G3 firmware is 3.3.2_0001.0004. Is that a problem? I did not see it on the supported list. How do you manually update the firmware to a specific version?
